title: My Blog  
description: My thoughts and projects  
#theme: minima  
remote_theme: mmistakes/minimal-mistakes

### MINIMAL MISTAKES STUFF

minimal_mistakes_skin: neon
#sass:
#	style: compressed

search: true
breadcrumbs: true

author:
  name: Micah Lundquist
  bio: man idek
  location: Earth
  links:
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/cuboooooo

### END MINIMAL MISTAKES

url: "https://blog.mlhost.org"
baseurl: ""

markdown: kramdown  
permalink: /:categories/:title/

plugins:  
- jekyll-include-cache
- jekyll-seo-tag
- jekyll-last-modified-at

last-modified-at:
  date-format: '%B %-d, %Y'

# truthfully idk what this is doing.
collections:
  vault:
    output: false