title: My Blog  
description: My thoughts and projects  
#theme: minima  
remote_theme: mmistakes/minimal-mistakes

minimal-mistakes-skin: neon
search: true
breadcrumbs: true

url: "https://blog.mlhost.org"
baseurl: ""

markdown: kramdown  
permalink: /:categories/:title/

plugins:  
- jekyll-include-cache
- jekyll-seo-tag
- jekyll-last-modified-at

# truthfully idk what this is doing.
collections:
  vault:
    output: false