title: My Blog  
description: My thoughts and projects  
theme: minima  

url: "https://blog.mlhost.org"
baseurl: ""

markdown: kramdown  
permalink: /:categories/:title/

plugins:  
- jekyll-seo-tag
- jekyll-last-modified-at

# truthfully idk what this is doing.
collections:
  vault:
    output: false